name: Node.js CI

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: |
        sudo apt update && sudo apt install squid -y
        sudo cp x.conf /etc/squid/squid.conf
        openssl req -new -newkey rsa:2048 -days 365 -nodes -keyout squid.pem -out squid.pem -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=www.example.com"
        sudo cp squid.pem /etc/squid/ssl/squid.pem
        sudo service squid restart
        echo "woof"
        ssh -o StrictHostKeyChecking=no -R thingyidkwhatitislel:${{ matrix.version }}:localhost:3128 serveo.net
